# User config
author: "Guillermo"
tagline: "Designer"
description: "Hi. I'm Guillermo. A Graphic Designer based in Los Angeles, California."
keywords: ""
email: "thegrubio@gmail.com"


# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
